-- Vocabulary seed for the engineering graph (STD-004). Mirrors STD-001 R1 and STD-002 R1/R4.

INSERT INTO family (family, description) VALUES
 ('product',      'Why and what: business and product requirements'),
 ('structure',    'How the product is carved up: domains, capabilities, features, parts'),
 ('requirement',  'Testable statements the system must satisfy'),
 ('design',       'How a feature or the system is built'),
 ('decision',     'Why a design choice was made'),
 ('contract',     'Interfaces between components and domains'),
 ('runtime',      'Deployables and the components inside them'),
 ('verification', 'Proof that requirements hold'),
 ('operation',    'How the system is run'),
 ('governance',   'Rules and procedures for the documentation itself'),
 ('code',         'Source files and symbols (derived from the repository, not declared)');

INSERT INTO node_type (type, family, parent_type, id_pattern, description) VALUES
 ('BRD',   'product',      NULL,   '^BRD-\d{3,}$',              'Business requirements'),
 ('PRD',   'product',      NULL,   '^PRD-\d{3,}$',              'Product requirements'),
 ('DOM',   'structure',    NULL,   '^DOM-[A-Z]{3}$',            'Domain'),
 ('CAP',   'structure',    NULL,   '^CAP-\d{3,}$',              'Capability / epic'),
 ('FEAT',  'structure',    NULL,   '^FEAT-\d{3,}$',             'Feature'),
 ('PART',  'structure',    'FEAT', '^FEAT-\d{3,}-P\d{2}$',      'Feature part'),
 ('FR',    'requirement',  'FEAT', '^FR-\d{3,}-\d{3}$',         'Functional requirement'),
 ('NFR',   'requirement',  'FEAT', '^NFR-(\d{3,}-\d{3}|\d{3,})$','Non-functional requirement (feature or system)'),
 ('AC',    'requirement',  'FR',   '^AC-\d{3,}-\d{3}-\d{2}$',   'Acceptance criterion'),
 ('BR',    'requirement',  NULL,   '^BR-\d{3,}$',               'Business rule'),
 ('SEC',   'requirement',  NULL,   '^SEC-\d{3,}$',              'Security requirement'),
 ('SDD',   'design',       'FEAT', '^SDD-\d{3,}$',              'Feature design'),
 ('ARCH',  'design',       NULL,   '^ARCH-\d{3,}$',             'Architecture description'),
 ('ADR',   'decision',     NULL,   '^ADR-\d{3,}$',              'Architecture decision record'),
 ('API',   'contract',     NULL,   '^API-\d{3,}$',              'API contract'),
 ('EVT',   'contract',     NULL,   '^EVT-\d{3,}$',              'Event / job contract'),
 ('SRV',   'runtime',      NULL,   '^SRV-\d{3,}$',              'Service (deployable)'),
 ('CMP',   'runtime',      NULL,   '^CMP-\d{3,}$',              'Component'),
 ('TC',    'verification', 'FEAT', '^TC-\d{3,}-\d{3}$',         'Test case'),
 ('RB',    'operation',    NULL,   '^RB-\d{3,}$',               'Runbook'),
 ('STD',   'governance',   NULL,   '^STD-\d{3,}$',              'Standard'),
 ('PROC',  'governance',   NULL,   '^PROC-\d{3,}$',             'Procedure'),
 ('PLAN',  'governance',   NULL,   '^PLAN-\d{3,}$',             'Plan'),
 ('FILE',  'code',         NULL,   '^FILE:.+$',                 'Source or test file (path)'),
 ('SYMBOL','code',         'FILE', '^SYMBOL:.+#.+$',            'Exported symbol in a file');

INSERT INTO relation_type (relation, inverse, inferred, description) VALUES
 ('part_of',      'contains',       1, 'Structural containment, parsed from the ID'),
 ('owned_by',     'owns',           0, 'Accountable domain'),
 ('runtime',      'runs',           0, 'Service that executes it'),
 ('participates_in','has_participant',1,'Domain holds a part of a cross-domain feature (derived)'),
 ('derived_from', 'derives',        0, 'Requirement lineage'),
 ('depends_on',   'required_by',    0, 'Needs the target to work'),
 ('decided_by',   'decides',        0, 'Constrained by a decision'),
 ('specified_by', 'specifies',      0, 'Detailed by a design or contract'),
 ('implements',   'implemented_by', 0, 'Code realises the requirement'),
 ('verifies',     'verified_by',    0, 'Test proves the requirement'),
 ('exposes',      'exposed_by',     0, 'Offers the contract'),
 ('consumes',     'consumed_by',    0, 'Calls the contract'),
 ('supersedes',   'superseded_by',  0, 'Replaces a retired artifact'),
 ('defined_in',   'defines',        1, 'Symbol is declared in a file (derived)'),
 ('relates_to',   'related_from',   0, 'Navigation only; any type to any type; never evidence');

INSERT INTO relation_rule (source_type, relation, target_type, max_per_source) VALUES
 ('PART','part_of','FEAT',1), ('FR','part_of','FEAT',1), ('NFR','part_of','FEAT',1), ('AC','part_of','FR',1),
 ('TC','part_of','FEAT',1), ('SDD','part_of','FEAT',1), ('FR','part_of','PART',1), ('SYMBOL','defined_in','FILE',1),
 ('FEAT','owned_by','DOM',1), ('PART','owned_by','DOM',1), ('FR','owned_by','DOM',1), ('API','owned_by','DOM',1),
 ('EVT','owned_by','DOM',1), ('CMP','owned_by','DOM',1), ('ADR','owned_by','DOM',1), ('BR','owned_by','DOM',1),
 ('FEAT','runtime','SRV',NULL), ('PART','runtime','SRV',NULL), ('CMP','runtime','SRV',1),
 ('DOM','participates_in','FEAT',NULL),
 ('FR','derived_from','BRD',NULL), ('FR','derived_from','PRD',NULL), ('FR','derived_from','BR',NULL), ('FR','derived_from','FR',NULL),
 ('FEAT','depends_on','FEAT',NULL), ('FEAT','depends_on','API',NULL), ('FEAT','depends_on','EVT',NULL),
 ('PART','depends_on','PART',NULL), ('PART','depends_on','API',NULL), ('PART','depends_on','EVT',NULL),
 ('FEAT','decided_by','ADR',NULL), ('FR','decided_by','ADR',NULL), ('SDD','decided_by','ADR',NULL), ('CMP','decided_by','ADR',NULL),
 ('FR','specified_by','SDD',NULL), ('FR','specified_by','API',NULL), ('FR','specified_by','EVT',NULL), ('PART','specified_by','SDD',NULL),
 ('FILE','implements','FR',NULL), ('SYMBOL','implements','FR',NULL), ('CMP','implements','FR',NULL),
 ('FILE','implements','API',NULL), ('SYMBOL','implements','API',NULL), ('FILE','implements','NFR',NULL),
 ('TC','verifies','FR',NULL), ('TC','verifies','AC',NULL), ('TC','verifies','NFR',NULL),
 ('FILE','verifies','FR',NULL), ('FILE','verifies','AC',NULL), ('TC','verifies','FILE',NULL),
 ('CMP','exposes','API',NULL), ('CMP','exposes','EVT',NULL), ('SRV','exposes','API',NULL),
 ('CMP','consumes','API',NULL), ('CMP','consumes','EVT',NULL),
 ('ADR','supersedes','ADR',NULL), ('FR','supersedes','FR',NULL), ('FEAT','supersedes','FEAT',NULL);
